//
//  HomePresenter.swift
//  UnsplashPhoto
//
//  Created by Admin on 18.11.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class HomePresenter {

    // MARK: - Private properties -

    private unowned let view: HomeViewInterface
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface
    private let bag = DisposeBag()

    // MARK: - Lifecycle -

    init(view: HomeViewInterface, interactor: HomeInteractorInterface, wireframe: HomeWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {

    func configure(with output: Home.ViewOutput) -> Home.ViewInput {
        
        output.loadMorePhotos
            .do(onNext: { [interactor] in
                if $0 == interactor.photosCount - 1 {
                    interactor.loadMorePhotos()
                }
            })
            .subscribe()
            .disposed(by: bag)
        
        output.photoSelected
            .do(onNext: { [wireframe] photo in
                wireframe.navigate(to: .imageDetail(image: photo))
            })
            .drive()
            .disposed(by: bag)
        
        
        return Home.ViewInput(
            photosDriver: interactor.photosObservable.asDriver(onErrorJustReturn: [])
        )
    }

}
