//
//  ImageDetailsPresenter.swift
//  UnsplashPhoto
//
//  Created by Admin on 30.11.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class ImageDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: ImageDetailsViewInterface
    private let interactor: ImageDetailsInteractorInterface
    private let wireframe: ImageDetailsWireframeInterface
    private let image: Photo
    private let bag = DisposeBag()

    // MARK: - Lifecycle -

    init(view: ImageDetailsViewInterface, interactor: ImageDetailsInteractorInterface, wireframe: ImageDetailsWireframeInterface, image: Photo) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.image = image
    }
}

// MARK: - Extensions -

extension ImageDetailsPresenter: ImageDetailsPresenterInterface {

    func configure(with output: ImageDetails.ViewOutput) -> ImageDetails.ViewInput {
        let photoDescription = image.photoDescription ?? image.altDescription ?? ""
        let photoImageUrl = URL(string: image.urls.full)
        
        return ImageDetails.ViewInput(
            photoDescription: .just(photoDescription),
            photoImageUrl: .just(photoImageUrl)
        )
    }

}
