//
//  ImageDetailsInterfaces.swift
//  UnsplashPhoto
//
//  Created by Admin on 30.11.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ImageDetailsWireframeInterface: WireframeInterface {
    
}

protocol ImageDetailsViewInterface: ViewInterface {
}

protocol ImageDetailsPresenterInterface: PresenterInterface {
    func configure(with output: ImageDetails.ViewOutput) -> ImageDetails.ViewInput
}

protocol ImageDetailsInteractorInterface: InteractorInterface {
}

enum ImageDetails {

    struct ViewOutput {
        
    }

    struct ViewInput {
        let photoDescription: Driver<String>
        let photoImageUrl: Driver<URL?>
    }

}
