//
//  ImageDetailsWireframe.swift
//  UnsplashPhoto
//
//  Created by Admin on 30.11.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ImageDetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "ImageDetails", bundle: nil)
    private let selectedImage: Photo

    // MARK: - Module setup -

    init(image: Photo) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ImageDetailsViewController.self)
        self.selectedImage = image
        super.init(viewController: moduleViewController)

        let interactor = ImageDetailsInteractor()
        let presenter = ImageDetailsPresenter(view: moduleViewController, interactor: interactor, wireframe: self, image: image)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension ImageDetailsWireframe: ImageDetailsWireframeInterface {
    
}
