//
//  ImageDetailsInteractor.swift
//  UnsplashPhoto
//
//  Created by Admin on 30.11.2020.
//  Copyright (c) 2020 Danil Semenov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ImageDetailsInteractor {
    
}

// MARK: - Extensions -

extension ImageDetailsInteractor: ImageDetailsInteractorInterface {
}
